### ISSUE TITLE
instr_timing test ROM fails with Failure #255

### ISSUE THREAD

**Issue by euclio** [afishberg/feo-boy#48]
This error message is non-sensical, but notably jsGB fails this test with the same code. I'm kind of at my wits' end, as I've confirmed that our timings are correct. Last resort is to step through the emulator alongside another one and see what differs.

Could be a timer issue? Interestingly, someone ran into the same error on NES instruction timing tests: https://forums.nesdev.com/viewtopic.php?t=4728&start=30.

Definitely appears to be a timer initialization issue. See https://bitbucket.org/arkhaix/emunisce/issues/6/check-opcode-timings.

**Comment by fizaan** [comment]
Were you able to resolve this issue? I’m running into the same failure.

**Comment by euclio** [comment]
Yes, the bug is that you may need to increment the timer multiple times while executing a single instruction: https://github.com/feo-boy/feo-boy/blob/master/src/bus/timer.rs#L56-L66
